[project]
name = "ssm-tool"
version = "0.1.0"
description = "AWS SSM toolkit for instance management and access"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34.0",
    "prettytable>=3.0.0",
    "python-dateutil>=2.8.1",
    "urllib3>=2.0.0",
]
